

def lyrics_raffa():
    phrases = [
    "Sério, eu não tô preocupado com os outros",
    "Sério, eu tô focado em ficar grande",
    "Sério, eu juro que eu não sou zé povinho",
    "Sério que você não paga meu lean",
    "Sério, no começo eu ganhava pouco",
    "Sério, eu nunca desfoquei do meu plano",
    "Tive que discordar de alguns manos",
    "E hoje todos eles me dão razão",
    "E eu me apeguei em Deus",
    "Não pensava em desistir",
    "E hoje eu coloco o cordão",
    "Pra fora da minha camisa",
    "Sério, não entendo, eles querem briga",
    "E se eu tiver sozinho eu vou tá armado",
    "Por isso sempre vou pra todos lugares",
    "Mochila nas costas ou bolsa de lado",
    "Oi, alô, quem é?",
    "Raffa",
    "Espera um pouco",
    "Quem tá falando?",
    "Melhor trocar ideia ao vivo",
    "Nós pula na sua quebrada hoje a noite",
    "Relaxa, mano, eu tô encostando agora",
    "Onde que cês mora? Manda o mapa",
    "Atrás da Estação, sobe o morro e vira",
    "No outro beco, nós ta no barraco",
    "Pulei no seu bloco",
    "De peça na bolsa, eu nunca pipoquei",
    "Eu ando com uma glock na mochila",
    "Mas eu sento e espero resolver",
    "Pulei no seu bloco",
    "De peça na bolsa, eu nunca pipoquei",
    "Eu não levei meu double cup",
    "Mas tinha na bolsa uma .40",
    "Raffa Moreira, mano",
    "Ei, Raffa (yeah)",
    "Sério, eu não tô preocupado com os outros",
    "Sério, eu tô focado em ficar grande",
    "Sério, eu juro que eu não sou zé povinho",
    "Sério que você não paga meu lean",
    "Sério, no começo eu ganhava pouco",
    "Sério, eu nunca desfoquei do meu plano",
    "Tive que discordar de alguns manos",
    "E hoje todos eles me dão razão",
    "Oi, alô, quem é?",
    "Raffa",
    "Espera um pouco",
    "Quem tá falando?",
    "Melhor trocar ideia ao vivo",
    "Nós pula na sua quebrada hoje a noite",
    "Relaxa, mano, eu tô encostando agora",
    "Onde que cês mora? Manda o mapa",
    "Não devo ninguém, nunca fui pra ideia",
    "Tudo certo na minha quebrada",
    "Sério, eu não tô preocupado com os outros",
    "Sério, mano, eu tô focado em progresso",
    "Deus me livre atrasar outros preto",
    "Ainda mais os que me deram acesso",
    "Tá moscando quem não sai da internet",
    "A inveja não pode apagar meu nome",
    "Sua luz não pode apagar meu brilho",
    "Consequência vai ser inevitável",
    "Vi o 6ix9ine passando por isso",
    "Então fuck twelve, eu não sou seu amigo",
    "Então fuck it, bro, foda-se a polícia",
    "Minha choppa tá na backpack Zara, então pull up",
    "Mano, para de me ligar, tipo",
    "Mano, nós não fala gang, gang, bro",
    "Nós não paga pau pra gringo",
    "Tralha do Rio de Janei-",
    "Real trap, você é fake",
    "Eu fiz isso pela gang, eu juro, isso é real",
    "Eu fui mais além, eu trouxe os meus comigo",
    "Primeiros shows viajei sozinho",
    "Avião, fone, hotel e uma bitch",
    "Em silêncio, sexo proibido",
    "Antes de ter meu próprio DJ",
    "Antes de ter um hit eu estourei no fone dos mais verdadeiro em todos puteiro",
    "Depois do hit 'Bro' pus elas pra quebrar",
    "Estourei no Norte e ainda sou o primeiro",
    "'Cê tenta copiar enquanto nós tá rico",
    "Eu tenho double cup, 'cê bebendo whisky",
    "Depois do meu show joguei um na piscina",
    "Meu Rider é barra 380",
    "Red Label é pouco, Black Label",
    "Eu amo bala gringa",
    "Cachê alto, abençoado",
    "Capital das notas, eu sou de São Paulo",
    "Garoa fina e eu tô congelado",
    "Neve no nariz (drip, drip, drip)",
    "iPhone, liguei pro Fuky",
    "E perguntei do Luizin'",
    "Miliano que eu não vejo",
    "Tá trampando lá no Kevin",
    "E eu sempre ligo o Magnum",
    "Vários irmãos no contato",
    "E esse é considerado",
    "Vários irmãos de verdade",
    "Neve no nariz (drip, drip, drip)",
    "Dez mil sozinho num mês",
    "Continuo independente",
    "Eu vim de baixo, talvez",
    "Não tinha tido minha vez",
    "Se tivesse ouvido aqueles",
    "Que não queriam meu bem",
    "Eles não querem seu bem",
    "Ouro e prata no meu dente",
    "O futuro de presente",
    "Gelo de coco e uma bitch",
    "Todos meus manos quase ricos",
    "Show toda semana, cash",
    "Eu tô viciado em dinheiro",
    "Acostumado com as fotos",
    "Não me preocupo com os falsos",
    "Subo nas coisas porque eu posso",
    "Faço dinheiro porque eu posso",
    "Alguns se chamando de trapstar",
    "Usando dinheiro dos seus pais",
    "Eu sei que é foda de criticar",
    "Bro, eu não preciso de empresário",
    "No último mês não fumei seda",
    "O patrocínio do som me mandou blunts",
    "Vem sobrando dinheiro pros blunts",
    "Incrível, as coisas tem mudado",
    "Na vila, os amigo comentaram",
    "E agora eles sabem quem é o raro",
    "E o meu carro novo na pista faz skr skr skr",
    "200 por hora",
    "E meu inimigos na duvida desacredita",
    "Perderam a aposta, 7-7-7",
    "Esse número multiplica todos na minha conta",
    "Gang gang bro",
    "Pus nomes no jogo",
    "Eu fiz isso pela minha mob, yeah",
    "FERNVNDX Clothing",
    "O Brasil inteiro esperando drop",
    "A drop nova eu vou mandar pro Hoffman",
    "Ele tem um plug, que é carioca",
    "Bebendo lean",
    "Bebendo lean",
    "Trancado no estúdio",
    "Produzindo um beat",
    "Gravando um hit",
    "Coração a zero",
    "Mano, eu tô gelado",
    "Faz frio, faz sol",
    "E eu de diamante",
    "VVS no meu pulso brilha",
    "Cor de gelo, metanfetamina",
    "Zero graus, bro, eu tenho jóias agora",
    "E eu não comprei em duas vezes",
    "Eu vim de tão baixo e eu tinha tão pouco",
    "Eu segui focado e eu mudei o jogo (prr)",
    "Dez mil sozinho num mês",
    "Continuo independente",
    "Eu vim de baixo, talvez",
    "Não tinha tido minha vez",
    "Se tivesse ouvido aqueles",
    "Que não queriam meu bem",
    "Eles não querem seu bem",
    "Ouro e prata no meu dente",
    "O futuro de presente",
    "Gelo de coco e uma bitch",
    "Todos meus manos quase ricos",
    "Show toda semana, cash",
    "Eu tô viciado em dinheiro",
    "Acostumado com as fotos",
    "Não me preocupo com os falsos",
    "Subo nas coisas porque eu posso",
    "Eyy, Raffa",
    "FERNVNDX Clothing nego",
    "Raffa Moreira mano",
    "777, (skr skr skr), ay ay ay",
    "Yeah, ay ay ay",
    "Bro, faz sol",
    "Camisa da FERNVNDX Clothing",
    "Eu soquei um hater no shopping",
    "Que falou bosta",
    "Uow, óculos do Kurt Cobain",
    "Double cup, Sprite, Codein",
    "Todo mundo fala de mim",
    "Joguei um beck de gr",
    "Na seda branca queima",
    "Joguei codeina na minha fanta",
    "Postei o lançamento da minha blusa",
    "Hater falou mal, ele é uma puta",
    "O que eu faço é hype, de fato eu sou foda",
    "Meus fãs reais nunca me viram as costas",
    "Eles acham minha calça apertada style",
    "Eles sabem sou gangsta paradise",
    "Yo, faz sol",
    "Camisa da FERNVNDX Clothing",
    "Eu soquei um hater no shopping",
    "Que falou bosta",
    "Wow, óculos do Kurt Cobain",
    "Double cup, Sprite, Codein",
    "Todo mundo fala de mim",
    "Todos os jovens agora falam minhas gírias",
    "Eles perguntam onde compro minhas roupas",
    "Por isso eu investi na minha marca",
    "Meu swag esta no nivel dez milhões",
    "Sai fora com essas marca de playboy tipo a palace",
    "FERNVNDX Clothing squad, squad raffa, não pare",
    "Ay, ay, ay, ay, ay",
    "Ay, ay, ay, ay, ay",
    "Ay, ay, ay, ay, ay",
    "Bro, faz sol",
    "Camisa da FERNVNDX Clothing",
    "Eu soquei um hater no shopping",
    "Que falou bosta",
    "Wow, óculos do Kurt Cobain",
    "Double cup, Sprite, Codein",
    "Todo mundo fala de mim",
    "Raffa Moreira mano",
    "Hey, hey",
    "Raffa, Raffa",

    "Pop tipo Michael Jackson",
    "Rico tipo Michael Jackson",
    "Louco tipo Michael Jackson",
    "Foda tipo Michael Jackson",

    "Preto tipo Michael Jackson",
    "Avançado Michael Jackson",
    "Raffa é tipo Michael Jackson",
    "Raffa é tipo Michael Jackson",

    "Raffa 777",
    "Pop tipo Michael Jackson",
    "Hype tipo Michael Jackson",
    "Ay, ay, Raffa Moreira",

    "Quem é esse Raffa Moreira?",
    "Foda esse Raffa Moreira",
    "Conheci o Raffa Moreira",
    "Trap não é Raffa Moreira",

    "Eu escutei Raffa Moreira",
    "Apoie Raffa Moreira",
    "Play play play play play",
    "Raffa Moreira",

    "Digo, mano",
    "Eu vou ganha o mundo e é fato",
    "Tipo o Cirilo na corrida de carro (skrt)",
    "Jovem Raffa, mano",
    "É tão FERNVNDX Clothing",
    "Nego, Raffa, me copiam",
    "Mas não cola",
    "Pop tipo Michael Jackson",
    "Rico tipo Michael Jackson",
    "Louco tipo Michael Jackson",
    "Foda tipo Michael Jackson",
    "Preto tipo Michael Jackson",
    "Avançado Michael Jackson",
    "Raffa 777",
    "Michael Jackson mixtape, mano",
    "Rei do pop, mano",
    "Raffa Rei do Trap, mano",
    "É o rei do trap mesmo (skrt, skrt, skrt)",
    "Quem é esse que tá cantando?",
    "Nego, é o Raffa Moreira",
    "Mano, o som dele é pesado",
    "Gang gang gang",
    "Ele é tipo Racionais",
    "Ele é o irmão do Brown",
    "Todos os meus manos sabem que o Racionais é influência na rua e na vida",
    "São pretos, meu mano",
    "Olhe em sua volta",
    "As virtudes, verdades",
    "São pretas, meu mano",
    "Clipe da Fiat 95 foi Thriller, meu mano",
    "Raffa Moreira novo Michael Jackson",
    "Quesito talento",
    "Sadboys Guarulhos Trap, yeah",
    "Pop tipo Michael Jackson",
    "Rico tipo Michael Jackson",
    "Louco tipo Michael Jackson",
    "Foda tipo Michael Jackson",
    "Preto tipo Michael Jackson",
    "Avançado Michael Jackson",
    "Raffa 777",
    "Ei, ei, Raffa, Raffa",
    "Mixtape, mano",
    "Michael Jackson Mixtape, mano",
    "Postei foto no face",
    "Raffa é foda?! Talvez",
    "No meu drink dei um gole",
    "Esses caras são mole",
    "Um otário comentou",
    "Ah, esse Raffa é de mentira",
    "Ele não assaltou o banco porra nenhuma",
    "Postei foto no face",
    "Som novo divulguei",
    "Esses caras são mole",
    "Foda-se quem não goste!",
    "Foda-se os meus views",
    "Seu trampo eu nunca vi",
    "Raffa, por que cê não estoura?",
    "Foda-se a moda",
    "Mano, eu tô suave",
    "Raffa é gol, eles trave",
    "Os caras acharam engraçado aquela porra",
    "Tipo Guarulhos Trap , yeah",
    "Os negos não entendem que eu tô um passo à frente do Sonic, Knuckles yeah",
    "O som na minha frente",
    "Escuta a free verse",
    "Eu sou Michael Jackson",
    "Vocês que me odeiam?!",
    "Cês são Freddy Krueger!",
    "Yeah, postei foto no face",
    "Raffa é foda?! Talvez",
    "No meu drink dei um gole",
    "Esses caras são mole",
    "Um otário comentou",
    "Ah, esse mano aí é mó paga pau de gringo",
    "Falou, hein?!",
    "Postei foto no face",
    "Som novo divulguei",
    "Esses caras são mole",
    "Eu nunca vi esses manos",
    "Cadê o trampo desses cara, mano?",
    "Cadê o vídeo desses cara, mano?",
    "Postei foto no face",
    "Vivo atrás dos plays",
    "Vivo atrás dos shows",
    "Vivo pela minhas filhas",
    "Vivo pelo meu vô",
    "Vivo pela minha mãe",
    "Salve pro DonCesão",
    "Salve Pokemón Go",
    "Salve lá pra Lisboa",
    "Eu sou o Michael Jackson, mano",
    "Michael Jackson mixtape, mano",
    "Raffa Moreira, mano",
    "FERNVNDX Clothing, nego",
    "Ha, ha, yeah",
    "Yeah",
    "Mais do que as críticas e todas as suas risadas",
    "Eu venho trabalhando, mantendo o foco, chapa",
    "Me questionaram sobre as camisetas, shirt rock",
    "A do Metallica eu dei risada, usei por troll",
    "Sobre FERNVNDX: Foi minha primeira mixtape",
    "Gravando tracks, mesmo precisando de um tênis",
    "Não admito críticas, cê escutou de graça",
    "Se quiser fazer um depósito, te mando a conta",
    "Foda-se seu dislike pra baixo, joia? Só no meu pescoço",
    "Spotify cê paga, Raffa é download (grátis)",
    "Eu costumava ser um nego querendo ir mais longe",
    "Eu sempre era questionado: Raffa, vai aonde?",
    "Eu pretendo tocar o céu, incentivando manos",
    "As feats, número de views, incentivando os manos",
    "Eu vim de baixo, negro alto, magro, alvo fácil, cara de assaltante",
    "Não é ficção free verse PSHIU!",
    "A polícia levou meu carro e eu senti ódio",
    "Tava só saindo da favela, como moro próximo",
    "Ouvindo raps sobre praia e belas mulheres",
    "Senti vazio, quero diferente pro meu rap",
    "Fuck",
    "Eu não tô preocupado bro",
    "Tipo, foda-se",
    "Fuck, fuck, fuck, fuck, fuck, fuck, fuck",
    "Fuck, fuck, fuck, fuck, fuck, fuck, bro",
    "Fuck bro",
    "Vocês viciados na porra do LOL (fuck)",
    "Raffa Moreira xingou a polícia, wow",
    "Beck à tarde",
    "Rockstar",
    "Negos me deem, oh yeah",
    "FERNVNDX Clothing, agora é grife",
    "Uma peça: 700",
    "Só gente style usa",
    "As minas perguntam da blusa",
    "Yeah, yeah, yeah",
    "E se você falar bosta",
    "Eu dou um tiro na sua cara",
    "Bang, bang, bang",
    "Fuck, fuck, fuck, fuck, fuck, fuck, fuck",
    "Acho que eu dei um tiro na sua vó",
    "Descanse em paz Fredo Santana",
    "Bro eu sempre cantei drill",
    "Eu amo o Brasil",
    "Meus fãs reais são do Brasil",
    "Eu sou o primeiro MC a ter fãs reais no Brasil (hahaha)",
    "Fuck, fuck, fuck, fuck, fuck hater",
    "Fuck, fuck, fuck, fuck, você é feio",
    "Você não tem maconha",
    "Determinado na guerra, estratégia, olho por olho",
    "Protejo o ouro, sei com quem eu corro",
    "Fase difícil, estrutura zero, noites no estúdio",
    "Noites no tráfico, me lembro do passado",
    "Conquistei, não foi fácil",
    "No carro automático eu ganhei boquete",
    "Uma noite, amanhã a bitch me esquece",
    "O brilho do meu diamante congela a inveja",
    "Eu tô confiante, então cala a boca",
    "Maninho, minha gangue é foda",
    "Cê tenta copiar, mas não pode, você é trouxa",
    "Meu mano, você quer ser alvejado eo dud bro",
    "Determinado na guerra, estratégia, olho por olho (yeah!)",
    "Protejo o ouro, sei com quem eu corro",
    "Fase difícil, estrutura zero, noites no estúdio (yeah!)",
    "Noites no tráfico, meu mano, cê não viveu isso",
    "4 e 10, pensando sozinho no Sukyia mais molho inglês",
    "15 reais com a Coca-Cola e eu já sou freguês",
    "Indo pro estúdio, a Zona Norte eu atravessei",
    "No rádio eu percebi quando eu entrei um som do (Worst)",
    "Deus, eles entendem o Drake",
    "Esses jovens todos são fãs de Future",
    "Eles amam o Thug, mas desprezam o Raffa",
    "Por causa do auto-tune que eles não conseguem reproduzir",
    "Como a todos MC's do Brasil",
    "Que desprezam a evolução por causa da frustração própria",
    "Eu fiz por mim e pela minha família",
    "Pensando no sukyia sozinho, como eu queria ser eterno",
    "Yeah, man",
    "Que se foda os hater",
    "Mano eu vi isso de longe",
    "Mano eu só corri por dentro",
    "Caralho uma par de invejoso",
    "Quem num me entendeu só lamento",
    "Eu recebi a carta do adsenses",
    "Eu vi esses manos todos mudando opinião",
    "Gravei 7 faixas numa noite com eles no pé",
    "Quem não gostou do Poetas não abala minha fé",
    "E foda-se",
    "Sento sozinho no Sukyia mais molho inglês",
    "15 reais com a Coca-Cola e eu ja sou freguês",
    "Indo pro estúdio, a Zona Norte eu atravessei",
    "No rádio, eu percebi quando eu entrei um som do Drake",
    "Não é só mais um",
    "Beat de trap, eu vo falar a verdade",
    "Tô por aí sempre, choppa na calça",
    "Sou Original, acompanha minha vibe, yeah",
    "Nike Jordan 1",
    "Portando grife eu tô fazendo história",
    "Mano que odeia, eu sei que é inveja",
    "Num arruma nada comigo na ideia",
    "Tava tudo bem",
    "Até você perrecar",
    "Slatt slatt, mó cobra",
    "Se é pussy, num fode ninguém",
    "Se sabe que eu sou de gang",
    "Tô com a pistola 380",
    "Ela vai te encontrar",
    "Igual o Doritos se vai tá frito e assado",
    "Réza pra eu não te achar",
    "Se tá sumido no trap fico no passado",
    "Eu tô contando esse money, yeah",
    "100 mil no meu advance, cash",
    "Nunca vi tanto dinheiro mas é porque eu tô merecendo",
    "Eu vo pra festa, sem hora pra acabar, hoje",
    "Mandei desce 10 garrafas só Jack, Johnny Walker",
    "Se viu meu camarim",
    "Percebeu que nós só fumo blunt",
    "Muita fumaça no ar",
    "Tô tranquilo eu tô na paz",
    "Se depender de mim",
    "A tropa vai seguir avançando e vai memo",
    "Os truta num deixa por menos",
    "Whisky maconha MD",
    "Tô me movimentando na cena",
    "Cachê alto pra evita poblema",
    "Triple X final da turne",
    "Ballenciaga Prada LV",
    "Coisas que eu nunca tive",
    "Rap tá me dando e o meu talento",
    "Tô pelas rua absorvendo",
    "Se virar eu vou ser rico pra sempre",
    "Tenho carro e eu ando de mochila",
    "Vou dispensar o B.O. na minha vila",
    "Estilo chucro no desbaratino",
    "Meto o loco os cóp no enquadro direto",
    "Só eles olhar na cara, já sei que é perréco",
    "Do trabalho pra duster pros força e pro tático",
    "Essa é vida gangster de um mano raro",
    "Essa podia te entrado no trap the fato",
    "Tô roletando de SUV",
    "Coisas que são da minha vivencia",
    "Se der uma zika eu tenho dinheiro meu advogado vai tá la presente",
    "Só todo errado mas tô pelo certo e o certo prevalece no acontecimento",
    "Meu relógio tá sempre no tempo",
    "Audemar Calvin Klein Cartier",
    "Cabelos longos escuros com lace",
    "Kim Kardashian com a pele negra",
    "Ela é gostosa e pensa pra frente",
    "Eu puis tudo nela e pressionei",
    "Ela tá olhada e quente a noite inteira",
    "Tá tremendo a perna eu tô só na primeira",
    "Tão popular quanto a Camila Cabelo",
    "Preferência nacional são os peito",
    "Prótese, tão grande, sexy, e eu amo",
    "Fashion, excitante, fato, Chandon",
    "É que toda vez ela bebe ela esquece o horario e até o lugar",
    "Sempre que eu me encontro com ela parece que o meu relógio tá parado",
    "Tik tak é noite",
    "Tempo passou voando",
    "Motel prive pernoite",
    "Hidromassagem e amor",
    "Pressão pressão",
    "Tik tak é noite",
    "Tempo passou voando",
    "Motel prive pernoite",
    "Hidromassagem e amor",
    "Pressão pressão",
    "Essa noite eu vou te macetar",
    "Na primeira banheira e depois no sofá",
    "Tô de Philipp plein mil reais na minha calça",
    "Grifes caras luxo designer",
    "Tudo o que eu tenho é nosso pra sempre",
    "Nossa união sempre foi diferente",
    "Kanye sempre foi referência",
    "College dropout sai da minha mente",
    "Espero que ele va pra Rehab",
    "North, Psalm Mr. West",
    "Essa vida pode ser só um teste",
    "Eu tô aprovado eu tenho muita fé",
    "Na boca dela eu encontrei o céu",
    "Quando eu tô com ela eu esqueço o resto",
    "Nos dois somos como Tory e a Megan",
    "Triste isso é verdade",
    "Por essa eu não esperava",
    "Eu mal posso entender tudo isso",
    "Meus problemas são grandes mas eu não desisto",
    "Tô no corre agora pra um dia ser rico",
    "Meu próximo advance mais de 6 digitos",
    "Tudo tem o momento e porque",
    "Nada acontece por acaso",
    "Eu e você foi já tava escrito",
    "Te vi e fiquei apaixonado",
    "Verdadeiro com quem corre comigo",
    "Eu não tenho amigos, tenho irmãos",
    "Calça suja, blusa, Fernvndx Clothing Co",
    "Derrubei lean no meu cordão de ouro",
    "Eu já repeti muito essas roupas",
    "Hoje eu compro nova toda semana",
    "Versace, Balmain, a loja na França",
    "Paris, Champs-Élysées e lean na minha fanta",
    "Orange kush, me chamam de trapstar",
    "Faria bem mais pela minha família",
    "Por isso eu trafiquei esses quilos",
    "Por isso eu corri em volta dos pesos",
    "Run!, eu pensava no dinheiro",
    "Filho pequeno, e todos os meus sonhos",
    "A polícia já me levou dois carros",
    "Eu não confio nesses arrombados",
    "Talvez não confie em ninguém",
    "Mas tenho meus erros também",
    "Se você testar alguém da gang",
    "Gang, gang, gang, gang!",
    "Meus niggas portam as griffes mais caras",
    "Mas não perdoamos mais de três vezes",
    "Se eu te avisei é draco na sua cara",
    "Segunda chance só no vídeo game",
    "Eles procuram problema comigo",
    "Eu procuro só por peças no shopping",
    "Maldita inveja, eu não compreendo",
    "Malditos haters querem me ver pobre",
    "Mas Deus jamais permitiu",
    "Deus olhou pela minha família",
    "Eu olhei pela minha família",
    "Por ela, eu tiraria sua vida",
    "Minha família coberta de ouro",
    "E que seja desse jeito pra sempre",
    "Allah, Assalamaleiko, Amen",
    "Double cup, Martin Luther King",
    "Ceia com meus irmãos, purple drink",
    "Confiante como Mike Tyson",
    "Inimigos com mal de Parkison",
    "Tentando me vencer, mas fracos são (yeah)",
    "E as drogas que eu jogo na sprite",
    "São fortes são, yeah",
    "São tão fortes quanto as rimas dos meus irmãos, yeah",
    "Então toda noite nós vamos fazer um brinde",
    "Que sejamos ricos em dinheiro e saúde",
    "Tesla Model, S3",
    "Skunk orange, de blunt ou de OG kush, a minha strain (bitch)",
    "Plantei um pé na minha estufa",
    "Esperei, deu fruto, eu nunca mais comprei (uh)",
    "Investi todo o meu lucro, liguei meus contatos, sucessos nas vendas",
    "Polícia é inimigo da gente, não tenho acerto com vocês, ayy",
    "Baile não para, eles me breca nunca (yeah)",
    "Quatrocentos reais na minha blusa",
    "Misturas diferentes no meu copo (ayy)",
    "Jacaré da Lacoste puxa a bandeira lá da loja",
    "Quem tentar ratiar os trampo dos parceiros vai tá fora (ayy)",
    "Quem traiu não tem perdão na história",
    "Aconselho é ficar longe do problema",
    "Beat do Jay Kay com Raffa é gol na certa",
    "Pulando na bitch sem medo (yeah)",
    "Misturando strains na minha seda (uh)",
    "Carnaval é só Fevereiro (yeah)",
    "Tô surfando o ano inteiro (splash)",
    "Ei, ei",
    "Raffa, Raffa, yeah (Nansy Silvvs)",
    "Mixtape mano, Rockstar",
    "Mixtape mano, Raffa rock, hey, yeah",

    "28 preto swag, 28 preto swag, 28 preto swag, 28 preto swag",
    "Eu comecei há mais de 10 anos, mano, no skate",
    "28 preto swag, 28 preto swag, 28 preto swag",
    "Calça apertada Rockstar",
    "Conveniência, drink, skate",
    "Mano, eu não quero estourar",
    "Foda-se a televisão, foda-se o dinheiro e o satã",
    "Foda-se essas ilusão, foda-se se você é maçom",
    "Foda-se, eu só quero andar de skate",
    "Foda-se as vadias e os hater",

    "28 preto swag, 38 Glock, preto gang",
    "Eu comecei há mais de 10 anos, mano, no skate",
    "Calça apertada, tênis velho, kick flip na base",
    "Calça apertada, foda-se se é a mesma do clipe, hey",
    "Eu uso as mesmas calças dos meus clipe pra andar de skate",
    "Analisando os manos com CD gravando mixtapes",

    "Moletom Fernando Clothing, cinco gramas na minha touca",
    "Duas passagem no meu nome, porque todo polícia é trouxa!",
    "Vi os cops na esquina, desacelerei o passo",
    "Essa noite, nego, eu sabia que pelo meu swag ia tomar enquadro",
    "Preto raro, rock, chave, lean, sprite, skate, trinca",
    "Android, fone, passe andando Nike, Adidas",
    "Encosta, mano, enquadro, mano, que faz, mano?",
    "Você canta, mano? É rap, mano?",
    "Raffa, por que cê não estoura?",
    "Faz um som tipo Projota",

    "28 preto swag, 28 preto swag, 28 preto swag, 28 preto swag",
    "Eu comecei há mais de 10 anos, mano, no skate",
    "28 preto swag, 28 preto swag, 28 preto swag",
    "Calça apertada rockstar",
    "Conveniência, drink, skate",
    "Mano eu não quero estourar, foda-se",
    "Foda-se a televisão, foda-se o dinheiro e o satã",
    "Foda-se essas ilusão, foda-se se você é maçom",

    "Raffa Moreira, mano",
    "Rockstar Mixtape, mano",
    "Dia primeiro de dezembro",
    "Bem-vindo Natal mixtape",
    "Yeah, yeah, gang",
    "Eu recusei o convite",
    "O Raffa é o mais criativo"

]
    return phrases



